Added CLI option to save disassembly file
nurpax/c64jasm pull request #69
Opened 2020-10-17 22:33 UTC by shazz

Hi,

This is a little patch to the CLI to, in addition to `stdout`, output the disassembly in a given file:

````
c64jasm sprites.asm --out sprites.prg --disasm-file debug.asm
c64jasm sprites.asm --out sprites.prg --disasm
````

2020-10-18 21:40 UTC, nurpax requested changes
Thanks for the patch @shazz!

I added some comments, kind of nitpicks but it's nice to keep the code tidy.  Would be great if you can fix those so I can merge your code directly (so that authorship is retained in git commit).

2020-10-18 21:40 UTC, nurpax commented on src/cli.ts
> +        try{
`try {` instead of `try{` :)

2020-10-18 21:40 UTC, nurpax commented on src/cli.ts
> +            console.log(`Generating ${args.disasmFile}`)
This print should go under the below `if (args.disasmfile)` so that it's only printed when using `--disasm-file`.

2020-10-18 21:40 UTC, nurpax commented on src/cli.ts
> +    help: 'Save the Disassembly in the give file.'
give -> given?

Disassembly -> disassembly (no capitalization needed here)

2020-10-21 23:10 UTC, shazz commented
Changes applied normally.

2021-02-05 23:42 UTC, nurpax commented
Closing as I think this change already went in in another change from @shazz

2021-02-05 23:42 UTC, closed without merging